import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head></Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Script
          id="qpop-widget"
          data-uid="67260ecafd2aa475def08604"
          src="https://widget.qpop.xyz/iframe-loader.js"
        ></Script>
        {children}
      </body>
    </html>
  );
}
